name: aplsurp-python-web
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - jupyter-book
  - ipykernel
  - ghp-import
  - folium
  - matplotlib
  - numpy
  - pandas
  - ctd
  - folium
  - gsw
  - seabird
  # - geopandas
  # - xarray
  # - seaborn
  # - cartopy

